#############################################################################
# Makefile for building: mere-about
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  mere-about.pro
# Template: app
# Command: /usr/local/lib/qt5/bin/qmake -o Makefile mere-about.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -pthread -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -pthread -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -I. -I/usr/local/include/libdrm -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang
QMAKE         = /usr/local/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mere-about1.0.0
DISTDIR = /usr/home/iklash/workspace/merelab/mere-about/.tmp/mere-about1.0.0
LINK          = clang++
LFLAGS        = -pthread -Wl,-rpath,/usr/local/lib/qt5
LIBS          = $(SUBLIBS) -L/usr/local/lib /usr/local/lib/qt5/libQt5Widgets.so /usr/local/lib/qt5/libQt5Gui.so /usr/local/lib/qt5/libQt5Core.so /usr/local/lib/libGL.so   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mereaboutapp.cpp \
		src/mereaboutwin.cpp qrc_about.cpp \
		moc_mereaboutapp.cpp \
		moc_mereaboutwin.cpp
OBJECTS       = main.o \
		mereaboutapp.o \
		mereaboutwin.o \
		qrc_about.o \
		moc_mereaboutapp.o \
		moc_mereaboutwin.o
DIST          = i18n/mere-about_bn.ts \
		i18n/mere-about_en.ts \
		/usr/local/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf \
		/usr/local/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/clang.conf \
		/usr/local/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_declarative.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		/usr/local/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/local/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/lib/qt5/mkspecs/features/uic.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/local/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/lib/qt5/mkspecs/features/lex.prf \
		mere-about.pro src/mereaboutapp.h \
		src/mereaboutwin.h src/main.cpp \
		src/mereaboutapp.cpp \
		src/mereaboutwin.cpp
QMAKE_TARGET  = mere-about
DESTDIR       = 
TARGET        = mere-about


first: all
####### Build rules

mere-about:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mere-about.pro /usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf /usr/local/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf \
		/usr/local/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/clang.conf \
		/usr/local/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_declarative.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		/usr/local/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/local/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/lib/qt5/mkspecs/features/uic.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/local/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/lib/qt5/mkspecs/features/lex.prf \
		mere-about.pro \
		res/about.qrc
	$(QMAKE) -o Makefile mere-about.pro
/usr/local/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/local/lib/qt5/mkspecs/common/unix.conf:
/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf:
/usr/local/lib/qt5/mkspecs/common/sanitize.conf:
/usr/local/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/local/lib/qt5/mkspecs/common/clang.conf:
/usr/local/lib/qt5/mkspecs/qconfig.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_declarative.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webview.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/local/lib/qt5/mkspecs/features/qt_config.prf:
/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf:
/usr/local/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/local/lib/qt5/mkspecs/features/toolchain.prf:
/usr/local/lib/qt5/mkspecs/features/default_pre.prf:
/usr/local/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/local/lib/qt5/mkspecs/features/default_post.prf:
/usr/local/lib/qt5/mkspecs/features/warn_on.prf:
/usr/local/lib/qt5/mkspecs/features/qt.prf:
/usr/local/lib/qt5/mkspecs/features/resources.prf:
/usr/local/lib/qt5/mkspecs/features/moc.prf:
/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/local/lib/qt5/mkspecs/features/uic.prf:
/usr/local/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/local/lib/qt5/mkspecs/features/qmake_use.prf:
/usr/local/lib/qt5/mkspecs/features/file_copies.prf:
/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/local/lib/qt5/mkspecs/features/exceptions.prf:
/usr/local/lib/qt5/mkspecs/features/yacc.prf:
/usr/local/lib/qt5/mkspecs/features/lex.prf:
mere-about.pro:
res/about.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile mere-about.pro

qmake_all: FORCE


all: Makefile mere-about

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/about.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mereaboutapp.h src/mereaboutwin.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mereaboutapp.cpp src/mereaboutwin.cpp $(DISTDIR)/
	$(COPY_FILE) --parents i18n/mere-about_en.ts i18n/mere-about_bn.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_about.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_about.cpp
qrc_about.cpp: res/about.qrc \
		/usr/local/lib/qt5/bin/rcc \
		res/about.qss \
		res/mere-logo.png \
		res/close-icon.png
	/usr/local/lib/qt5/bin/rcc -name about res/about.qrc -o qrc_about.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp
	clang++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mereaboutapp.cpp moc_mereaboutwin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mereaboutapp.cpp moc_mereaboutwin.cpp
moc_mereaboutapp.cpp: src/mereaboutapp.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtCore/QTranslator \
		/usr/local/include/qt5/QtCore/qtranslator.h \
		/usr/local/include/qt5/QtWidgets/QApplication \
		/usr/local/include/qt5/QtWidgets/qapplication.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtCore/qcoreapplication.h \
		/usr/local/include/qt5/QtCore/qeventloop.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qpainterpath.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtGui/qguiapplication.h \
		/usr/local/include/qt5/QtGui/qinputmethod.h \
		moc_predefs.h \
		/usr/local/lib/qt5/bin/moc
	/usr/local/lib/qt5/bin/moc $(DEFINES) --include /usr/home/iklash/workspace/merelab/mere-about/moc_predefs.h -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I/usr/home/iklash/workspace/merelab/mere-about -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -I/usr/include/c++/v1 -I/usr/lib/clang/8.0.0/include -I/usr/include src/mereaboutapp.h -o moc_mereaboutapp.cpp

moc_mereaboutwin.cpp: src/mereaboutwin.h \
		/usr/local/include/qt5/QtWidgets/QLabel \
		/usr/local/include/qt5/QtWidgets/qlabel.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtWidgets/qframe.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qpainterpath.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtWidgets/QWidget \
		/usr/local/include/qt5/QtCore/QDebug \
		moc_predefs.h \
		/usr/local/lib/qt5/bin/moc
	/usr/local/lib/qt5/bin/moc $(DEFINES) --include /usr/home/iklash/workspace/merelab/mere-about/moc_predefs.h -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I/usr/home/iklash/workspace/merelab/mere-about -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -I/usr/include/c++/v1 -I/usr/lib/clang/8.0.0/include -I/usr/include src/mereaboutwin.h -o moc_mereaboutwin.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/mereaboutapp.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtCore/QTranslator \
		/usr/local/include/qt5/QtCore/qtranslator.h \
		/usr/local/include/qt5/QtWidgets/QApplication \
		/usr/local/include/qt5/QtWidgets/qapplication.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtCore/qcoreapplication.h \
		/usr/local/include/qt5/QtCore/qeventloop.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qpainterpath.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtGui/qguiapplication.h \
		/usr/local/include/qt5/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mereaboutapp.o: src/mereaboutapp.cpp src/mereaboutapp.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtCore/QTranslator \
		/usr/local/include/qt5/QtCore/qtranslator.h \
		/usr/local/include/qt5/QtWidgets/QApplication \
		/usr/local/include/qt5/QtWidgets/qapplication.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtCore/qcoreapplication.h \
		/usr/local/include/qt5/QtCore/qeventloop.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qpainterpath.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtGui/qguiapplication.h \
		/usr/local/include/qt5/QtGui/qinputmethod.h \
		src/mereaboutwin.h \
		/usr/local/include/qt5/QtWidgets/QLabel \
		/usr/local/include/qt5/QtWidgets/qlabel.h \
		/usr/local/include/qt5/QtWidgets/qframe.h \
		/usr/local/include/qt5/QtWidgets/QWidget \
		/usr/local/include/qt5/QtCore/QFileInfo \
		/usr/local/include/qt5/QtCore/qfileinfo.h \
		/usr/local/include/qt5/QtCore/QLocale
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mereaboutapp.o src/mereaboutapp.cpp

mereaboutwin.o: src/mereaboutwin.cpp src/mereaboutwin.h \
		/usr/local/include/qt5/QtWidgets/QLabel \
		/usr/local/include/qt5/QtWidgets/qlabel.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtWidgets/qframe.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qpainterpath.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtWidgets/QWidget \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtGui/QIcon \
		/usr/local/include/qt5/QtGui/qicon.h \
		/usr/local/include/qt5/QtGui/QScreen \
		/usr/local/include/qt5/QtGui/qscreen.h \
		/usr/local/include/qt5/QtCore/QList \
		/usr/local/include/qt5/QtCore/QObject \
		/usr/local/include/qt5/QtCore/QRect \
		/usr/local/include/qt5/QtCore/QSize \
		/usr/local/include/qt5/QtCore/QSizeF \
		/usr/local/include/qt5/QtGui/QTransform \
		/usr/local/include/qt5/QtWidgets/QPushButton \
		/usr/local/include/qt5/QtWidgets/qpushbutton.h \
		/usr/local/include/qt5/QtWidgets/qabstractbutton.h \
		/usr/local/include/qt5/QtWidgets/QApplication \
		/usr/local/include/qt5/QtWidgets/qapplication.h \
		/usr/local/include/qt5/QtCore/qcoreapplication.h \
		/usr/local/include/qt5/QtCore/qeventloop.h \
		/usr/local/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/local/include/qt5/QtGui/qguiapplication.h \
		/usr/local/include/qt5/QtGui/qinputmethod.h \
		/usr/local/include/qt5/QtWidgets/QDesktopWidget \
		/usr/local/include/qt5/QtWidgets/QHBoxLayout \
		/usr/local/include/qt5/QtWidgets/qboxlayout.h \
		/usr/local/include/qt5/QtWidgets/qlayout.h \
		/usr/local/include/qt5/QtWidgets/qlayoutitem.h \
		/usr/local/include/qt5/QtWidgets/qgridlayout.h \
		/usr/local/include/qt5/QtWidgets/QVBoxLayout
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mereaboutwin.o src/mereaboutwin.cpp

qrc_about.o: qrc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_about.o qrc_about.cpp

moc_mereaboutapp.o: moc_mereaboutapp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mereaboutapp.o moc_mereaboutapp.cpp

moc_mereaboutwin.o: moc_mereaboutwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mereaboutwin.o moc_mereaboutwin.cpp

####### Install

install_i18n: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/mere/about/i18n || mkdir -p $(INSTALL_ROOT)/usr/local/share/mere/about/i18n
	-$(QINSTALL) /usr/home/iklash/workspace/merelab/mere-about/i18n/mere-about_en.qm $(INSTALL_ROOT)/usr/local/share/mere/about/i18n/mere-about_en.qm
	-$(QINSTALL) /usr/home/iklash/workspace/merelab/mere-about/i18n/mere-about_bn.qm $(INSTALL_ROOT)/usr/local/share/mere/about/i18n/mere-about_bn.qm

uninstall_i18n: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/mere/about/i18n/mere-about_bn.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/mere/about/i18n/mere-about_en.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/mere/about/i18n/ 


install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/bin || mkdir -p $(INSTALL_ROOT)/usr/local/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install: install_i18n install_target  FORCE

uninstall: uninstall_i18n uninstall_target  FORCE

FORCE:

