#############################################################################
# Makefile for building: mere-about
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  mere-about.pro
# Template: app
# Command: /usr/local/lib/qt5/bin/qmake -o Makefile mere-about.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -pthread -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -pthread -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -I. -I/usr/local/include -I/usr/local/include/libdrm -I. -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang
QMAKE         = /usr/local/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mere-about1.0.0
DISTDIR = /usr/home/iklash/workspace/mere/mere-about/.tmp/mere-about1.0.0
LINK          = clang++
LFLAGS        = -pthread -Wl,-rpath,/usr/local/lib/qt5
LIBS          = $(SUBLIBS) -L/lib -L/usr/local/lib -L/usr/local/lib/qt5 -lQt5Widgets -lQt5Gui -lQt5Core -lkvm -lprocstat -lGL 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mereaboutwindow.cpp qrc_res.cpp \
		moc_mereaboutwindow.cpp
OBJECTS       = main.o \
		mereaboutwindow.o \
		qrc_res.o \
		moc_mereaboutwindow.o
DIST          = /usr/local/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf \
		/usr/local/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/clang.conf \
		/usr/local/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_CalendarSupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_ContactEditor.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_EventViews.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_FollowupReminder.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_GrantleeTheme.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Gravatar.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_IncidenceEditor.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KaddressbookGrantlee.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KaddressbookImportExport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KBlog.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCalCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCalUtils.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCddb.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KChart.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCompactDisc.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_kdav.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KdepimDBusInterfaces.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGantt.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPICore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIMAP.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Kirigami2.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KMailTransport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KMailTransportAkonadi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KManageSieve.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KontactInterface.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KService.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KSieve.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KSieveUi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KSMTP.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KTNef.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Ldap.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Libkdepim.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_LibkdepimAkonadi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Libkleo.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MailCommon.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MailImporter.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MailImporterAkonadi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Marble.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Mbox.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MessageComposer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MessageCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MessageList.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MessageViewer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MimeTreeParser.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_PimCommon.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_PimCommonAkonadi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_SendLater.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Syndication.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_TemplateParser.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_WebEngineViewer.pri \
		/usr/local/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		/usr/local/lib/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/local/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/lib/qt5/mkspecs/features/uic.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/local/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/lib/qt5/mkspecs/features/lex.prf \
		mere-about.pro src/mereaboutwindow.h src/main.cpp \
		src/mereaboutwindow.cpp
QMAKE_TARGET  = mere-about
DESTDIR       = 
TARGET        = mere-about


first: all
####### Build rules

$(TARGET): ui_mainframe.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mere-about.pro /usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf /usr/local/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf \
		/usr/local/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/clang.conf \
		/usr/local/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_CalendarSupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_ContactEditor.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_EventViews.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_FollowupReminder.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_GrantleeTheme.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Gravatar.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_IncidenceEditor.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KaddressbookGrantlee.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KaddressbookImportExport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KBlog.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCalCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCalUtils.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCddb.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KChart.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCompactDisc.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_kdav.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KdepimDBusInterfaces.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGantt.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPICore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIMAP.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Kirigami2.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KMailTransport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KMailTransportAkonadi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KManageSieve.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KontactInterface.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KService.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KSieve.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KSieveUi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KSMTP.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KTNef.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Ldap.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Libkdepim.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_LibkdepimAkonadi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Libkleo.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MailCommon.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MailImporter.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MailImporterAkonadi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Marble.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Mbox.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MessageComposer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MessageCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MessageList.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MessageViewer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_MimeTreeParser.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_PimCommon.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_PimCommonAkonadi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_SendLater.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_Syndication.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_TemplateParser.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_WebEngineViewer.pri \
		/usr/local/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		/usr/local/lib/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/local/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/lib/qt5/mkspecs/features/uic.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/local/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/lib/qt5/mkspecs/features/lex.prf \
		mere-about.pro \
		res/res.qrc \
		/usr/local/lib/qt5/libQt5Widgets.prl \
		/usr/local/lib/qt5/libQt5Gui.prl \
		/usr/local/lib/qt5/libQt5Core.prl
	$(QMAKE) -o Makefile mere-about.pro
/usr/local/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/local/lib/qt5/mkspecs/common/unix.conf:
/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf:
/usr/local/lib/qt5/mkspecs/common/sanitize.conf:
/usr/local/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/local/lib/qt5/mkspecs/common/clang.conf:
/usr/local/lib/qt5/mkspecs/qconfig.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiCalendar.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiContact.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiCore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiMime.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiNotes.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiWidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_AkonadiXml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Attica.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_CalendarSupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_quick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_ContactEditor.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_EventViews.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_FollowupReminder.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_GrantleeTheme.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Gravatar.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_IncidenceEditor.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KActivities.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KaddressbookGrantlee.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KaddressbookImportExport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KAlarmCal.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KArchive.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KBlog.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KBookmarks.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KCalCore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KCalUtils.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KCddb.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KChart.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KCMUtils.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KCompactDisc.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KCompletion.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KContacts.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KCrash.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_kdav.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KDeclarative.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KdepimDBusInterfaces.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KDESu.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KDEWebKit.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KDNSSD.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KEmoticons.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KFileMetaData.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGantt.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIBlogger.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGAPICalendar.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIContacts.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGAPICore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIDrive.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGAPILatitude.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGAPIMaps.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGAPITasks.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KGuiAddons.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KHolidays.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KHtml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KIconThemes.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KIdentityManagement.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KIdleTime.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KIMAP.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KIOCore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KIOGui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KIOWidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Kirigami2.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KItemModels.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KJS.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KJSApi.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KJsEmbed.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KMailTransport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KMailTransportAkonadi.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KManageSieve.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KMime.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KNewStuff.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KNotifications.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KNTLM.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KontactInterface.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KParts.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KPeople.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KPIMTextEdit.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KPlotting.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KPty.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KrossCore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KrossUi.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KRunner.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KScreen.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KService.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KSieve.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KSieveUi.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KSMTP.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KTextEditor.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KTextWidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KTNef.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KUnitConversion.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KWallet.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KWaylandClient.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KWaylandServer.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KXmlGui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_KXmlRpcClient.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Ldap.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Libkdepim.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_LibkdepimAkonadi.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Libkleo.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_MailCommon.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_MailImporter.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_MailImporterAkonadi.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Marble.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Mbox.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_MessageComposer.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_MessageCore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_MessageList.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_MessageViewer.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_MimeTreeParser.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_phonon4qt5.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_PimCommon.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_PimCommonAkonadi.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Prison.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_QuickAddons.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_SendLater.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Solid.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_SonnetCore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_SonnetUi.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_Syndication.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_TemplateParser.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_WebEngineViewer.pri:
/usr/local/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/local/lib/qt5/mkspecs/features/qt_config.prf:
/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf:
/usr/local/lib/qt5/mkspecs/features/spec_post.prf:
../.qmake.stash:
/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/local/lib/qt5/mkspecs/features/toolchain.prf:
/usr/local/lib/qt5/mkspecs/features/default_pre.prf:
/usr/local/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/local/lib/qt5/mkspecs/features/default_post.prf:
/usr/local/lib/qt5/mkspecs/features/warn_on.prf:
/usr/local/lib/qt5/mkspecs/features/qt.prf:
/usr/local/lib/qt5/mkspecs/features/resources.prf:
/usr/local/lib/qt5/mkspecs/features/moc.prf:
/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/local/lib/qt5/mkspecs/features/uic.prf:
/usr/local/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/local/lib/qt5/mkspecs/features/qmake_use.prf:
/usr/local/lib/qt5/mkspecs/features/file_copies.prf:
/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/local/lib/qt5/mkspecs/features/exceptions.prf:
/usr/local/lib/qt5/mkspecs/features/yacc.prf:
/usr/local/lib/qt5/mkspecs/features/lex.prf:
mere-about.pro:
res/res.qrc:
/usr/local/lib/qt5/libQt5Widgets.prl:
/usr/local/lib/qt5/libQt5Gui.prl:
/usr/local/lib/qt5/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile mere-about.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mereaboutwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mereaboutwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents res/mainframe.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res/res.qrc \
		/usr/local/lib/qt5/bin/rcc \
		res/mere-logo.png \
		res/close-icon.png
	/usr/local/lib/qt5/bin/rcc -name res res/res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp
	clang++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mereaboutwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mereaboutwindow.cpp
moc_mereaboutwindow.cpp: /usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-quick.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtWidgets/QMainWindow \
		/usr/local/include/qt5/QtWidgets/qmainwindow.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qpainterpath.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtWidgets/qtabwidget.h \
		/usr/local/include/qt5/QtGui/qicon.h \
		src/mereaboutwindow.h \
		moc_predefs.h \
		/usr/local/lib/qt5/bin/moc
	/usr/local/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I/usr/home/iklash/workspace/mere/mere-about -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -I/usr/include/c++/v1 -I/usr/lib/clang/6.0.0/include -I/usr/include src/mereaboutwindow.h -o moc_mereaboutwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainframe.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainframe.h
ui_mainframe.h: res/mainframe.ui \
		/usr/local/lib/qt5/bin/uic
	/usr/local/lib/qt5/bin/uic res/mainframe.ui -o ui_mainframe.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mereaboutwindow.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-quick.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtWidgets/QMainWindow \
		/usr/local/include/qt5/QtWidgets/qmainwindow.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qpainterpath.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtWidgets/qtabwidget.h \
		/usr/local/include/qt5/QtGui/qicon.h \
		/usr/local/include/qt5/QtWidgets/QApplication \
		/usr/local/include/qt5/QtWidgets/qapplication.h \
		/usr/local/include/qt5/QtCore/qcoreapplication.h \
		/usr/local/include/qt5/QtCore/qeventloop.h \
		/usr/local/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/local/include/qt5/QtGui/qguiapplication.h \
		/usr/local/include/qt5/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mereaboutwindow.o: src/mereaboutwindow.cpp src/mereaboutwindow.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-quick.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtWidgets/QMainWindow \
		/usr/local/include/qt5/QtWidgets/qmainwindow.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qpainterpath.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtWidgets/qtabwidget.h \
		/usr/local/include/qt5/QtGui/qicon.h \
		/usr/local/include/qt5/QtWidgets/QDesktopWidget \
		/usr/local/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/local/include/qt5/QtGui/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mereaboutwindow.o src/mereaboutwindow.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_mereaboutwindow.o: moc_mereaboutwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mereaboutwindow.o moc_mereaboutwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/bin || mkdir -p $(INSTALL_ROOT)/usr/local/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

